### ISSUE TITLE
Curious about the debugging setup, etc..

### ISSUE THREAD

**Issue by rub8n** [obs1dium/BetterManual#3]
Hello!

Great starting point you put together here.

Could you provide some pointers around the project setup, debugging setup/workflow (do you debug against the camera itself, emulator or what?)?

Having those as part of a getting started would be really helpful to those who would like to better understand how this works. 

Thanks!

**Comment by obs1dium** [comment]
I'm using AndroidStudio to build the project. You'll need the API level 10 SDK and 20.0.0 build tools.

You can only test on the camera itself, and there's no debugging mechanism... So the usual workflow looks something like this:

- Generate a signed APK
- Install it on the camera using the command line [pmca tool](https://github.com/ma1co/Sony-PMCA-RE/releases)
- Run and test the app (and then remove the battery from the camera if things go south)

Since there's no debugging I simply output stuff to the screen or log to the SD card.

The Sony APIs are undocumented, so there's a lot of trial and error going on.

**Comment by rub8n** [comment]
Got it. Thanks for the info.. will try to look into this soon!
